<script setup>
import { onMounted, ref, watch } from 'vue'
import { api } from '../api'
import { Users, RefreshCw, Search } from 'lucide-vue-next'
const followers=ref([]),total=ref(0),accounts=ref([]),accountId=ref(''),keyword=ref(''),error=ref(''),syncing=ref(false)
async function load(){try{const q=new URLSearchParams({page:'1',pageSize:'100'});if(accountId.value)q.set('accountId',accountId.value);if(keyword.value)q.set('keyword',keyword.value);const r=await api(`/api/followers?${q}`);followers.value=r.items;total.value=r.total}catch(e){error.value=e.message}}
async function sync(){if(!accountId.value){error.value='请先选择一个公众号';return}syncing.value=true;try{await api(`/api/followers/sync/${accountId.value}`,{method:'POST'});await load()}catch(e){error.value=e.message}finally{syncing.value=false}}
watch(accountId,load);let timer;watch(keyword,()=>{clearTimeout(timer);timer=setTimeout(load,300)});onMounted(async()=>{accounts.value=await api('/api/accounts').catch(()=>[]);load()})
</script>
<template><section class="page-content"><div class="section-heading"><div><span class="eyebrow">AUDIENCE</span><h2>了解每一位关注者</h2><p>按公众号同步 OpenID、UnionID、标签和关注状态。</p></div><button class="primary-button" :disabled="syncing" @click="sync"><RefreshCw :class="{spin:syncing}" :size="17" />同步用户</button></div><div class="filter-bar"><label class="search-input"><Search :size="16"/><input v-model="keyword" placeholder="搜索昵称、备注或 OpenID"></label><select v-model="accountId" class="compact-select"><option value="">全部公众号</option><option v-for="a in accounts" :key="a.id" :value="a.id">{{a.name}}</option></select><span class="filter-count">{{total}} 位用户</span></div><div v-if="error" class="alert error">{{error}}</div><div class="data-table panel"><div class="table-row table-header"><span>用户</span><span>公众号</span><span>OpenID</span><span>标签</span><span>状态</span></div><div v-for="u in followers" :key="u.id" class="table-row"><span class="user-cell"><img v-if="u.avatarUrl" :src="u.avatarUrl"><i v-else>{{(u.nickname||'用').slice(0,1)}}</i><strong>{{u.nickname||'微信用户'}}</strong></span><span>{{u.accountName}}</span><code>{{u.openId}}</code><span>{{u.tags||'—'}}</span><span class="status-pill" :class="u.subscribed?'connected':'failed'">{{u.subscribed?'已关注':'已取关'}}</span></div><div v-if="!followers.length" class="empty-state"><Users :size="31"/><strong>还没有同步用户</strong><p>选择公众号后点击“同步用户”。</p></div></div></section></template>
