<script setup>
import { onMounted, ref, watch } from 'vue'
import { api } from '../api'
import { useI18n } from '../i18n'
import { Users, RefreshCw, Search } from 'lucide-vue-next'
const followers=ref([]),total=ref(0),accounts=ref([]),accountId=ref(''),keyword=ref(''),error=ref(''),syncing=ref(false)
const { t } = useI18n()
async function load(){try{const q=new URLSearchParams({page:'1',pageSize:'100'});if(accountId.value)q.set('accountId',accountId.value);if(keyword.value)q.set('keyword',keyword.value);const r=await api(`/api/followers?${q}`);followers.value=r.items;total.value=r.total}catch(e){error.value=e.message}}
async function sync(){if(!accountId.value){error.value=t('followers.pleaseSelect');return}syncing.value=true;try{await api(`/api/followers/sync/${accountId.value}`,{method:'POST'});await load()}catch(e){error.value=e.message}finally{syncing.value=false}}
watch(accountId,load);let timer;watch(keyword,()=>{clearTimeout(timer);timer=setTimeout(load,300)});onMounted(async()=>{accounts.value=await api('/api/accounts').catch(()=>[]);load()})
</script>
<template><section class="page-content"><div class="section-heading"><div><span class="eyebrow">AUDIENCE</span><h2>{{ t('followers.title') }}</h2><p>{{ t('followers.description') }}</p></div><button class="primary-button" :disabled="syncing" @click="sync"><RefreshCw :class="{spin:syncing}" :size="17" />{{ t('followers.sync') }}</button></div><div class="filter-bar"><label class="search-input"><Search :size="16"/><input v-model="keyword" :placeholder="t('followers.searchPlaceholder')"></label><select v-model="accountId" class="compact-select"><option value="">{{ t('followers.allAccounts') }}</option><option v-for="a in accounts" :key="a.id" :value="a.id">{{a.name}}</option></select><span class="filter-count">{{ t('followers.count',{count:total}) }}</span></div><div v-if="error" class="alert error">{{error}}</div><div class="data-table panel"><div class="table-row table-header"><span>{{ t('followers.user') }}</span><span>{{ t('followers.account') }}</span><span>OpenID</span><span>{{ t('followers.tags') }}</span><span>{{ t('common.status') }}</span></div><div v-for="u in followers" :key="u.id" class="table-row"><span class="user-cell"><img v-if="u.avatarUrl" :src="u.avatarUrl"><i v-else>{{(u.nickname||t('followers.userInitial')).slice(0,1)}}</i><strong>{{u.nickname||t('followers.wechatUser')}}</strong></span><span>{{u.accountName}}</span><code>{{u.openId}}</code><span>{{u.tags||t('common.none')}}</span><span class="status-pill" :class="u.subscribed?'connected':'failed'">{{u.subscribed?t('followers.subscribed'):t('followers.unsubscribed')}}</span></div><div v-if="!followers.length" class="empty-state"><Users :size="31"/><strong>{{ t('followers.empty') }}</strong><p>{{ t('followers.emptyDescription') }}</p></div></div></section></template>
