<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { api } from '../api'
import { useI18n } from '../i18n'
import { Plus, Sparkles, Pencil, Trash2, X, Star, Search, Eye, RefreshCw, LoaderCircle } from 'lucide-vue-next'
const skills=ref([]), query=ref(''), error=ref(''), showForm=ref(false), saving=ref(false), viewing=ref(false), previewing=ref(null), generating=ref('')
const { t } = useI18n()
const form=reactive({id:null,name:'',description:'',content:''})
const filtered=computed(()=>skills.value.filter(skill=>`${skill.name} ${skill.description} ${skill.content}`.toLowerCase().includes(query.value.toLowerCase())))
async function load(){try{skills.value=await api('/api/skills')}catch(e){error.value=e.message}}
function open(skill,readOnly=false){Object.assign(form,{id:null,name:'',description:'',content:''},skill||{});viewing.value=readOnly;showForm.value=true;error.value=''}
const skillKey=skill=>skill.classpathResources||String(skill.id)
function showPreview(skill){if(skill.previewHtml)previewing.value=skill}
async function save(){if(saving.value)return;saving.value=true;try{const saved=await api(form.id?`/api/skills/${form.id}`:'/api/skills',{method:form.id?'PUT':'POST',body:JSON.stringify({name:form.name,description:form.description,content:form.content})});showForm.value=false;await load();const refreshed=skills.value.find(skill=>skill.id===saved.id);if(refreshed?.previewHtml)showPreview(refreshed);else if(saved.previewError)error.value=saved.previewError}catch(e){error.value=e.message}finally{saving.value=false}}
async function regenerate(skill){const key=skillKey(skill);if(generating.value)return;generating.value=key;error.value='';try{const result=await api(`/api/skills/${skill.id}/preview`,{method:'POST'});await load();const refreshed=skills.value.find(item=>item.id===result.id);if(refreshed?.previewHtml)showPreview(refreshed);else error.value=result.previewError||t('skills.previewFailed')}catch(e){error.value=e.message}finally{generating.value=''}}
async function remove(skill){if(!confirm(t('skills.deleteConfirm',{name:skill.name})))return;try{await api(`/api/skills/${skill.id}`,{method:'DELETE'});await load()}catch(e){error.value=e.message}}
onMounted(load)
</script>

<template>
  <section class="page-content">
    <div class="section-heading"><div><span class="eyebrow">ARTICLE SKILLS</span><h2>{{ t('skills.title') }}</h2><p>{{ t('skills.description') }}</p></div><button class="primary-button" @click="open()"><Plus :size="17"/>{{ t('skills.new') }}</button></div>
    <div v-if="error&&!showForm" class="alert error">{{error}}</div>
    <label class="skill-search"><Search :size="17"/><input v-model="query" :placeholder="t('skills.searchPlaceholder')" :aria-label="t('skills.searchPlaceholder')"></label>
    <div class="skill-grid">
      <article v-for="skill in filtered" :key="skill.classpathResources||skill.id" class="skill-card">
        <header><span class="skill-icon"><Sparkles :size="20"/></span><span v-if="skill.isDefault" class="skill-default"><Star :size="13"/>{{ t('skills.default') }}</span></header>
        <button class="skill-title" @click="open(skill,true)">{{skill.name}}</button><p>{{skill.description||t('skills.noDescription')}}</p>
        <div v-if="skill.previewHtml" class="skill-preview" role="button" tabindex="0" :aria-label="t('skills.previewTitle',{name:skill.name})" @click="showPreview(skill)" @keydown.enter.prevent="showPreview(skill)" @keydown.space.prevent="showPreview(skill)"><iframe :srcdoc="skill.previewHtml" sandbox="" loading="lazy" tabindex="-1" aria-hidden="true"></iframe><span><Eye :size="14"/>{{t('skills.openPreview')}}</span></div>
        <div v-else class="skill-preview-empty" :class="{failed:skill.previewStatus==='FAILED'}"><LoaderCircle v-if="skill.previewStatus==='GENERATING'" class="spin" :size="22"/><Sparkles v-else :size="22"/><strong>{{skill.previewStatus==='GENERATING'?t('skills.generatingPreview'):skill.previewStatus==='FAILED'?t('skills.previewFailed'):t('skills.previewPending')}}</strong><small v-if="skill.previewError">{{skill.previewError}}</small></div>
        <footer><button v-if="skill.previewHtml" class="text-button" @click="showPreview(skill)"><Eye :size="14"/>{{t('skills.preview')}}</button><button class="text-button" @click="open(skill,true)">{{ t('common.view') }}</button><button v-if="!skill.builtIn" class="text-button" @click="open(skill)"><Pencil :size="14"/>{{ t('common.edit') }}</button><button v-if="!skill.builtIn&&(skill.previewStatus==='FAILED'||!skill.previewHtml)" class="text-button" :disabled="generating===skillKey(skill)" @click="regenerate(skill)"><LoaderCircle v-if="generating===skillKey(skill)" class="spin" :size="14"/><RefreshCw v-else :size="14"/>{{t('skills.regenerate')}}</button><button v-if="!skill.builtIn" class="icon-button danger-ghost" :title="t('skills.removeTitle')" @click="remove(skill)"><Trash2 :size="16"/></button></footer>
      </article>
    </div>
    <div v-if="!filtered.length" class="empty-state">{{ t('skills.empty') }}</div>
    <div v-if="showForm" class="modal-backdrop"><form class="modal-card wide skill-modal" @submit.prevent="save"><header><h3>{{viewing?t('skills.view'):form.id?t('skills.edit'):t('skills.new')}}</h3><button type="button" class="icon-button" @click="showForm=false"><X :size="19"/></button></header><div v-if="error" class="alert error">{{error}}</div><div class="form-grid">
      <label class="full">{{ t('skills.name') }}<input v-model="form.name" required maxlength="255" :readonly="viewing" :placeholder="t('skills.namePlaceholder')"></label>
      <label class="full">{{ t('skills.descriptionLabel') }}<input v-model="form.description" maxlength="1000" :readonly="viewing" :placeholder="t('skills.descriptionPlaceholder')"></label>
      <label class="full">{{ t('skills.content') }}<textarea v-model="form.content" required maxlength="60000" rows="18" :readonly="viewing" :placeholder="t('skills.contentPlaceholder')"></textarea><small>{{ t('skills.contentHint') }}</small></label>
    </div><div class="form-actions"><button type="button" class="secondary-button" @click="showForm=false">{{ t('common.close') }}</button><button v-if="viewing&&!form.builtIn" type="button" class="primary-button" @click="viewing=false">{{ t('skills.edit') }}</button><button v-else-if="!viewing" class="primary-button" :disabled="saving"><LoaderCircle v-if="saving" class="spin" :size="15"/>{{saving?t('skills.savingPreview'):t('common.save')}}</button></div></form></div>
    <div v-if="previewing" class="modal-backdrop preview-backdrop"><section class="modal-card skill-preview-modal"><header><div><span class="eyebrow">HTML PREVIEW</span><h3>{{previewing.name}}</h3><p>{{previewing.description}}</p></div><button type="button" class="icon-button" @click="previewing=null"><X :size="19"/></button></header><iframe :title="t('skills.previewTitle',{name:previewing.name})" :srcdoc="previewing.previewHtml" sandbox=""></iframe></section></div>
  </section>
</template>

<style scoped>
.skill-search{display:flex;align-items:center;gap:10px;background:white;border:1px solid #e5e7eb;border-radius:9px;padding:8px 12px;max-width:450px;margin-bottom:24px;color:#888}.skill-search input{border:0;outline:none;width:100%;padding:4px}.skill-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:20px}.skill-card{background:white;border:1px solid #e6e9e7;border-radius:14px;padding:20px;overflow:hidden}.skill-card header,.skill-card footer{display:flex;align-items:center;gap:12px}.skill-card header{justify-content:space-between;margin-bottom:14px}.skill-icon{background:#edf8f1;color:#259565;padding:10px;border-radius:12px}.skill-default{display:flex;align-items:center;gap:5px;color:#168455;font-size:12px}.skill-title{border:0;background:none;font:inherit;font-size:18px;font-weight:600;text-align:left;cursor:pointer;padding:0}.skill-card>p{font-size:13px;color:#888;min-height:38px;margin-bottom:14px}.skill-preview{position:relative;display:block;width:100%;height:190px;padding:0;overflow:hidden;border:1px solid #e5e9e7;border-radius:10px;background:#f6f8f7;cursor:pointer}.skill-preview iframe{width:100%;height:100%;border:0;pointer-events:none;background:white}.skill-preview span{position:absolute;right:10px;bottom:10px;display:flex;align-items:center;gap:5px;padding:6px 9px;border-radius:7px;background:rgba(20,30,25,.78);color:white;font-size:11px;backdrop-filter:blur(8px)}.skill-preview-empty{height:190px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;padding:18px;border:1px dashed #cad6d0;border-radius:10px;background:#f8faf9;color:#708078;text-align:center}.skill-preview-empty.failed{border-color:#efc7c7;background:#fff8f8;color:#a94b4b}.skill-preview-empty strong{font-size:13px}.skill-preview-empty small{max-height:50px;overflow:hidden;font-size:11px}.skill-card footer{margin-top:16px;flex-wrap:wrap}.skill-card footer .icon-button{margin-left:auto}.skill-modal textarea{font:13px/1.7 ui-monospace,monospace;resize:vertical}.preview-backdrop{z-index:120}.skill-preview-modal{width:min(1100px,94vw);height:min(86vh,900px);display:flex;flex-direction:column;padding:0;overflow:hidden}.skill-preview-modal>header{padding:20px 24px;border-bottom:1px solid #e6e9e7}.skill-preview-modal>header h3{margin:2px 0}.skill-preview-modal>header p{margin:2px 0 0;color:#888;font-size:13px}.skill-preview-modal>iframe{flex:1;width:100%;border:0;background:white}
</style>
