<script setup>
import { onMounted, reactive, ref } from 'vue'
import { api } from '../api'
import { useI18n } from '../i18n'
import { Plus, UserCog, MoreHorizontal, X, KeyRound } from 'lucide-vue-next'
const users=ref([]),error=ref(''),showForm=ref(false),passwordFor=ref(null)
const { t, locale } = useI18n()
const blank=()=>({id:null,username:'',displayName:'',password:'',role:'EDITOR',status:'ACTIVE'});const form=reactive(blank())
async function load(){try{users.value=await api('/api/system-users')}catch(e){error.value=e.message}}
function open(u){Object.assign(form,blank(),u||{});showForm.value=true}
async function save(){try{await api(form.id?`/api/system-users/${form.id}`:'/api/system-users',{method:form.id?'PUT':'POST',body:JSON.stringify(form)});showForm.value=false;load()}catch(e){error.value=e.message}}
async function reset(){const p=prompt(t('users.resetPassword',{name:passwordFor.value.displayName}));if(!p)return;try{await api(`/api/system-users/${passwordFor.value.id}/password`,{method:'POST',body:JSON.stringify({password:p})});passwordFor.value=null}catch(e){error.value=e.message}}
onMounted(load)
</script>
<template><section class="page-content"><div class="section-heading"><div><span class="eyebrow">TEAM ACCESS</span><h2>{{ t('users.title') }}</h2><p>{{ t('users.description') }}</p></div><button class="primary-button" @click="open()"><Plus :size="17"/>{{ t('users.add') }}</button></div><div v-if="error" class="alert error">{{error}}</div><div class="data-table panel"><div class="table-row users-table table-header"><span>{{ t('users.user') }}</span><span>{{ t('users.role') }}</span><span>{{ t('common.status') }}</span><span>{{ t('users.lastLogin') }}</span><span></span></div><div v-for="u in users" :key="u.id" class="table-row users-table"><span class="user-cell"><i>{{u.displayName.slice(0,1)}}</i><span><strong>{{u.displayName}}</strong><small>@{{u.username}}</small></span></span><span class="role-badge">{{t(`users.roles.${u.role}`)}}</span><span class="status-pill" :class="u.status==='ACTIVE'?'connected':'failed'">{{u.status}}</span><span>{{u.lastLoginAt?new Date(u.lastLoginAt).toLocaleString(locale):t('users.neverLoggedIn')}}</span><span class="row-actions"><button class="icon-button" @click="passwordFor=u;reset()"><KeyRound :size="16"/></button><button class="icon-button" @click="open(u)"><MoreHorizontal :size="17"/></button></span></div><div v-if="!users.length" class="empty-state"><UserCog/><strong>{{ t('users.empty') }}</strong></div></div>
<div v-if="showForm" class="modal-backdrop"><form class="modal-card" @submit.prevent="save"><header><div><span class="eyebrow">USER ACCESS</span><h3>{{form.id?t('users.edit'):t('users.add')}}</h3></div><button type="button" class="icon-button" @click="showForm=false"><X :size="19"/></button></header><div class="form-grid"><label>{{ t('users.displayName') }}<input v-model="form.displayName" required></label><label>{{ t('users.username') }}<input v-model="form.username" :disabled="form.id" required></label><label v-if="!form.id">{{ t('users.initialPassword') }}<input v-model="form.password" type="password" minlength="8" required></label><label>{{ t('users.role') }}<select v-model="form.role"><option value="ADMIN">{{ t('users.roles.ADMIN') }}</option><option value="OPERATOR">{{ t('users.roles.OPERATOR') }}</option><option value="EDITOR">{{ t('users.roles.EDITOR') }}</option><option value="REVIEWER">{{ t('users.roles.REVIEWER') }}</option><option value="VIEWER">{{ t('users.roles.VIEWER') }}</option></select></label><label v-if="form.id">{{ t('common.status') }}<select v-model="form.status"><option value="ACTIVE">{{ t('common.enabled') }}</option><option value="DISABLED">{{ t('common.disabled') }}</option></select></label></div><div class="form-actions"><button type="button" class="secondary-button" @click="showForm=false">{{ t('common.cancel') }}</button><button class="primary-button">{{ t('users.save') }}</button></div></form></div></section></template>
