<script setup>
import { onMounted, reactive, ref } from 'vue'
import { api } from '../api'
import { Plus, UserCog, MoreHorizontal, X, KeyRound } from 'lucide-vue-next'
const users=ref([]),error=ref(''),showForm=ref(false),passwordFor=ref(null)
const blank=()=>({id:null,username:'',displayName:'',password:'',role:'EDITOR',status:'ACTIVE'});const form=reactive(blank())
async function load(){try{users.value=await api('/api/system-users')}catch(e){error.value=e.message}}
function open(u){Object.assign(form,blank(),u||{});showForm.value=true}
async function save(){try{await api(form.id?`/api/system-users/${form.id}`:'/api/system-users',{method:form.id?'PUT':'POST',body:JSON.stringify(form)});showForm.value=false;load()}catch(e){error.value=e.message}}
async function reset(){const p=prompt(`为 ${passwordFor.value.displayName} 设置新密码（至少 8 位）`);if(!p)return;try{await api(`/api/system-users/${passwordFor.value.id}/password`,{method:'POST',body:JSON.stringify({password:p})});passwordFor.value=null}catch(e){error.value=e.message}}
onMounted(load)
</script>
<template><section class="page-content"><div class="section-heading"><div><span class="eyebrow">TEAM ACCESS</span><h2>系统用户与权限</h2><p>为管理员、运营、编辑和审核人员分配恰当权限。</p></div><button class="primary-button" @click="open()"><Plus :size="17"/>添加用户</button></div><div v-if="error" class="alert error">{{error}}</div><div class="data-table panel"><div class="table-row users-table table-header"><span>用户</span><span>角色</span><span>状态</span><span>最近登录</span><span></span></div><div v-for="u in users" :key="u.id" class="table-row users-table"><span class="user-cell"><i>{{u.displayName.slice(0,1)}}</i><span><strong>{{u.displayName}}</strong><small>@{{u.username}}</small></span></span><span class="role-badge">{{u.role}}</span><span class="status-pill" :class="u.status==='ACTIVE'?'connected':'failed'">{{u.status}}</span><span>{{u.lastLoginAt?new Date(u.lastLoginAt).toLocaleString('zh-CN'):'从未登录'}}</span><span class="row-actions"><button class="icon-button" @click="passwordFor=u;reset()"><KeyRound :size="16"/></button><button class="icon-button" @click="open(u)"><MoreHorizontal :size="17"/></button></span></div><div v-if="!users.length" class="empty-state"><UserCog/><strong>暂无系统用户</strong></div></div>
<div v-if="showForm" class="modal-backdrop" @click.self="showForm=false"><form class="modal-card" @submit.prevent="save"><header><div><span class="eyebrow">USER ACCESS</span><h3>{{form.id?'编辑系统用户':'添加系统用户'}}</h3></div><button type="button" class="icon-button" @click="showForm=false"><X :size="19"/></button></header><div class="form-grid"><label>显示名称<input v-model="form.displayName" required></label><label>用户名<input v-model="form.username" :disabled="form.id" required></label><label v-if="!form.id">初始密码<input v-model="form.password" type="password" minlength="8" required></label><label>角色<select v-model="form.role"><option value="ADMIN">超级管理员</option><option value="OPERATOR">运营管理员</option><option value="EDITOR">编辑</option><option value="REVIEWER">审核员</option><option value="VIEWER">观察者</option></select></label><label v-if="form.id">状态<select v-model="form.status"><option value="ACTIVE">启用</option><option value="DISABLED">停用</option></select></label></div><div class="form-actions"><button type="button" class="secondary-button" @click="showForm=false">取消</button><button class="primary-button">保存用户</button></div></form></div></section></template>
